import JSZip from 'jszip';
import { WebsiteStructure } from '@/lib/types/website';
import { HTMLGenerator } from './html-generator';

export class ExportService {
  private htmlGenerator: HTMLGenerator;

  constructor() {
    this.htmlGenerator = new HTMLGenerator();
  }

  async exportAsZip(website: WebsiteStructure): Promise<Blob> {
    const zip = new JSZip();
    const html = this.htmlGenerator.generateFullHTML(website);

    // Add main HTML file
    zip.file('index.html', html);

    // Add README
    zip.file(
      'README.md',
      `# ${website.metadata.title}\n\n${website.metadata.description}\n\nGenerated by AI Website Builder`
    );

    // Add assets folder structure
    const assetsFolder = zip.folder('assets');
    if (assetsFolder && website.assets.length > 0) {
      website.assets.forEach((asset) => {
        // Note: In production, you'd need to fetch and include actual asset files
        assetsFolder.file(`${asset.id}.${asset.type}`, '');
      });
    }

    return await zip.generateAsync({ type: 'blob' });
  }

  exportAsHTML(website: WebsiteStructure): string {
    return this.htmlGenerator.generateFullHTML(website);
  }

  exportAsJSON(website: WebsiteStructure): string {
    return JSON.stringify(website, null, 2);
  }

  downloadFile(content: string | Blob, filename: string, mimeType?: string): void {
    const blob = typeof content === 'string' ? new Blob([content], { type: mimeType || 'text/plain' }) : content;
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}
